name: Pipeline Flask App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        run: |
          pytest

      - name: Artifact upload repo
        uses: actions/upload-artifact@v4
        with:
          name: Artifact
          path: |
            src/app
            Dockerfile
            requirements.txt

  Dockerfile-publish:
    needs: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Artifact download repo
        uses: actions/download-artifact@v5
        with:
          name: Artifact

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.run_number }}
      
  Create-kind-cluster:
    needs: Dockerfile-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up cluster
        uses: engineerd/setup-kind@v0.6.2

      - name: Apply manifests
        run: |
          docker build -t  gabrielcarl/flask-app:latest .
          kind load docker-image gabrielcarl/flask-app:latest
          kubectl apply -f k8s/
      
      - name: Get IP and NodePort
        run: |
          echo URL="http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane):$(kubectl get svc hello-port -o jsonpath='{.spec.ports[0].nodePort}')" >> $GITHUB_ENV
          echo {{ env.URL }}
      - name: Test deployment
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Set pytest
        uses: actions/setup-python@v5

      - name: Pytest requests
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          pytest tests/http_test_requests.py


      





