name: Pipeline Flask App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        run: |
          pytest

      - name: Artifact upload repo
        uses: actions/upload-artifact@v4
        with:
          name: Artifact
          path: |
            src/app
            Dockerfile
            requirements.txt

      - name: Artifact upload repo2
        uses: actions/upload-artifact@v4
        with:
          name: Artifact2
          path: |
            k8s/*
            tests/http_test_requests.py


  Dockerfile-publish:
    needs: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Artifact download repo
        uses: actions/download-artifact@v5
        with:
          name: Artifact

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.run_number }}

      - name: Set output
        id: docker_image
        run: echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/flask-app:latest" >> $GITHUB_OUTPUT

    outputs:
      image: ${{ steps.docker_image.outputs.IMAGE }}
      
  Create-kind-cluster:
    needs: Dockerfile-publish
    runs-on: ubuntu-latest
    steps:
      - name: Artifact download repo
        uses: actions/download-artifact@v5
        with:
          name: Artifact2

      - name: Set up cluster
        uses: engineerd/setup-kind@v0.6.2

      - name: Apply manifests
        run: |
          docker pull ${{ needs.Dockerfile-publish.outputs.image }}
          kind load docker-image ${{ needs.Dockerfile-publish.outputs.image }}
          kubectl apply --record -f k8s/
      
      - name: Get IP and NodePort
        run: |
          echo URL="http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane):$(kubectl get svc hello-port -o jsonpath='{.spec.ports[0].nodePort}')" >> $GITHUB_ENV
          echo $URL

      - name: Test deployment
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Set pytest
        uses: actions/setup-python@v5

      - name: Pytest requests
        run: |
          if [ -z "$URL" ]; then echo "URL is not set"; exit 1; fi
          while ! curl -s $URL/health; do sleep 5; done
          python -m pip install --upgrade pip
          pip install pytest requests
          pytest tests/http_test_requests.py